# numpy >> numerical python
# 2005 by Travis Oliphant

In [1]:
import numpy as np  # importing a numpy

In [3]:
np.__version__

'1.25.2'

In [9]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
lis  = [1,2,3,'azaz' , True , 1.2 , 3+2j]
type(lis)

list

In [7]:
lis

[1, 2, 3, 'azaz', True, 1.2, (3+2j)]

***numpy stores the data in a array***

***array is the container used to store the data od a same data type***


why NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items

  2. Fast mathematical operations over arrays
  
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [14]:
l = [1,2,3,4,5]
arr = np.array(l)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [17]:
l = [1,2,3,4,5.5]
arr = np.array(l)

In [19]:
arr # homogeneous items

array([1. , 2. , 3. , 4. , 5.5])

In [20]:
type(arr)

numpy.ndarray

In [22]:
arr.ndim

1

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1.ndim

2

***more way to convert array***

In [28]:
mat = np.matrix([1,2,3,4,5,6])
mat   #matrix is a specialised array , 2 dimensional 

matrix([[1, 2, 3, 4, 5, 6]])

In [29]:
type(mat)

numpy.matrix

In [30]:
l = [12,3,4,5,6,7]
arr2 = np.asarray(l)

arr2

array([12,  3,  4,  5,  6,  7])

In [33]:
mat = np.matrix[[1,2,3,4,5]]
print(mat)

numpy.matrix[[1, 2, 3, 4, 5]]


In [35]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [36]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
arr[0] = 500
arr[0]

500

In [42]:
arr

array([500,   2,   3,   4,   5,   6])

# Shallow Copy

In [44]:
a = arr
a

array([500,   2,   3,   4,   5,   6])

In [46]:
arr[0] = 5000
a               # change in array also lead to change in a >> Shallow copy

array([5000,    2,    3,    4,    5,    6])


# DeepCopy

In [48]:
a = arr.copy()

In [49]:
a

array([5000,    2,    3,    4,    5,    6])

In [50]:
arr[0] = 1000

In [53]:
a # Not change in a A bt using Deep Copy

array([5000,    2,    3,    4,    5,    6])

In [54]:
arr  

array([1000,    2,    3,    4,    5,    6])

***To Create an array  >> np.array , np.asarray , np.asanyarray , deep copy , shallow copy***

***Multiple way to generate a array***

In [57]:
arr = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

In [58]:
arr.ndim

2

In [59]:
arr.shape    #shape of array

(3, 3)

In [60]:
arr.size  # no of element i array

9

In [62]:
arr = np.fromfunction(lambda i, j: i *j, (3, 3), dtype=int)

arr

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [63]:
for i in range(5):
    print(i)

0
1
2
3
4


In [65]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [67]:
np.fromstring('22 55 66' ,sep = '  ')

array([22., 55., 66.])

In [69]:
str = 'azaz,lux,babu'
str1 = str.split(',')
print(np.array(str1)) 

['azaz' 'lux' 'babu']


In [70]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [71]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [73]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])